#include <errno.h>

#ifdef __APPLE__
#define ERROR_MESSAGES                                                         \
  {                                                                            \
      [0] = "Success",                                                         \
      [EPERM] = "Operation not permitted",                                     \
      [ENOENT] = "No such file or directory",                                  \
      [ESRCH] = "No such process",                                             \
      [EINTR] = "Interrupted system call",                                     \
      [EIO] = "Input/output error",                                            \
      [ENXIO] = "Device not configured",                                       \
      [E2BIG] = "Argument list too long",                                      \
      [ENOEXEC] = "Exec format error",                                         \
      [EBADF] = "Bad file descriptor",                                         \
      [ECHILD] = "No child processes",                                         \
      [EDEADLK] = "Resource deadlock avoided",                                 \
      [ENOMEM] = "Cannot allocate memory",                                     \
      [EACCES] = "Permission denied",                                          \
      [EFAULT] = "Bad address",                                                \
      [ENOTBLK] = "Block device required",                                     \
      [EBUSY] = "Device / Resource busy",                                      \
      [EEXIST] = "File exists",                                                \
      [EXDEV] = "Cross-device link",                                           \
      [ENODEV] = "Operation not supported by device",                          \
      [ENOTDIR] = "Not a directory",                                           \
      [EISDIR] = "Is a directory",                                             \
      [EINVAL] = "Invalid argument",                                           \
      [ENFILE] = "Too many open files in system",                              \
      [EMFILE] = "Too many open files",                                        \
      [ENOTTY] = "Inappropriate ioctl for device",                             \
      [ETXTBSY] = "Text file busy",                                            \
      [EFBIG] = "File too large",                                              \
      [ENOSPC] = "No space left on device",                                    \
      [ESPIPE] = "Illegal seek",                                               \
      [EROFS] = "Read-only file system",                                       \
      [EMLINK] = "Too many links",                                             \
      [EPIPE] = "Broken pipe",                                                 \
      [EDOM] = "Numerical argument out of domain",                             \
      [ERANGE] = "Result too large",                                           \
      [EAGAIN] = "Resource temporarily unavailable",                           \
      [EINPROGRESS] = "Operation now in progress",                             \
      [EALREADY] = "Operation already in progress",                            \
      [ENOTSOCK] = "Socket operation on non-socket",                           \
      [EDESTADDRREQ] = "Destination address required",                         \
      [EMSGSIZE] = "Message too long",                                         \
      [EPROTOTYPE] = "Protocol wrong type for socket",                         \
      [ENOPROTOOPT] = "Protocol not available",                                \
      [EPROTONOSUPPORT] = "Protocol not supported",                            \
      [ESOCKTNOSUPPORT] = "Socket type not supported",                         \
      [ENOTSUP] = "Operation not supported",                                   \
      [EPFNOSUPPORT] = "Protocol family not supported",                        \
      [EAFNOSUPPORT] = "Address family not supported by protocol family",      \
      [EADDRINUSE] = "Address already in use",                                 \
      [EADDRNOTAVAIL] = "Can't assign requested address",                      \
      [ENETDOWN] = "Network is down",                                          \
      [ENETUNREACH] = "Network is unreachable",                                \
      [ENETRESET] = "Network dropped connection on reset",                     \
      [ECONNABORTED] = "Software caused connection abort",                     \
      [ECONNRESET] = "Connection reset by peer",                               \
      [ENOBUFS] = "No buffer space available",                                 \
      [EISCONN] = "Socket is already connected",                               \
      [ENOTCONN] = "Socket is not connected",                                  \
      [ESHUTDOWN] = "Can't send after socket shutdown",                        \
      [ETOOMANYREFS] = "Too many references: can't splice",                    \
      [ETIMEDOUT] = "Operation timed out",                                     \
      [ECONNREFUSED] = "Connection refused",                                   \
      [ELOOP] = "Too many levels of symbolic links",                           \
      [ENAMETOOLONG] = "File name too long",                                   \
      [EHOSTDOWN] = "Host is down",                                            \
      [EHOSTUNREACH] = "No route to host",                                     \
      [ENOTEMPTY] = "Directory not empty",                                     \
      [EPROCLIM] = "Too many processes",                                       \
      [EUSERS] = "Too many users",                                             \
      [EDQUOT] = "Disc quota exceeded",                                        \
      [ESTALE] = "Stale NFS file handle",                                      \
      [EREMOTE] = "Too many levels of remote in path",                         \
      [EBADRPC] = "RPC struct is bad",                                         \
      [ERPCMISMATCH] = "RPC version wrong",                                    \
      [EPROGUNAVAIL] = "RPC prog. not avail",                                  \
      [EPROGMISMATCH] = "Program version wrong",                               \
      [EPROCUNAVAIL] = "Bad procedure for program",                            \
      [ENOLCK] = "No locks available",                                         \
      [ENOSYS] = "Function not implemented",                                   \
      [EFTYPE] = "Inappropriate file type or format",                          \
      [EAUTH] = "Authentication error",                                        \
      [ENEEDAUTH] = "Need authenticator",                                      \
      [EPWROFF] = "Device power is off",                                       \
      [EDEVERR] = "Device error",                                              \
      [EOVERFLOW] = "Value too large to be stored in data type",               \
      [EBADEXEC] = "Bad executable",                                           \
      [EBADARCH] = "Bad CPU type in executable",                               \
      [ESHLIBVERS] = "Shared library version mismatch",                        \
      [EBADMACHO] = "Malformed Macho file",                                    \
      [ECANCELED] = "Operation canceled",                                      \
      [EIDRM] = "Identifier removed",                                          \
      [ENOMSG] = "No message of desired type",                                 \
      [EILSEQ] = "Illegal byte sequence",                                      \
      [ENOATTR] = "Attribute not found",                                       \
      [EBADMSG] = "Bad message",                                               \
      [EMULTIHOP] = "Reserved",                                                \
      [ENODATA] = "No message available on STREAM",                            \
      [ENOLINK] = "Reserved",                                                  \
      [ENOSR] = "No STREAM resources",                                         \
      [ENOSTR] = "Not a STREAM",                                               \
      [EPROTO] = "Protocol error",                                             \
      [ETIME] = "STREAM ioctl timeout",                                        \
      [EOPNOTSUPP] = "Operation not supported on socket",                      \
  }
#define MAX_ERRNO 107

#elif __linux__
#define ERROR_MESSAGES                                                         \
  {                                                                            \
      [0] = "Success",                                                         \
      [EPERM] = "Operation not permitted",                                     \
      [ENOENT] = "No such file or directory",                                  \
      [ESRCH] = "No such process",                                             \
      [EINTR] = "Interrupted system call",                                     \
      [EIO] = "Input/output error",                                            \
      [ENXIO] = "No such device or address",                                   \
      [E2BIG] = "Argument list too long",                                      \
      [ENOEXEC] = "Exec format error",                                         \
      [EBADF] = "Bad file descriptor",                                         \
      [ECHILD] = "No child processes",                                         \
      [EAGAIN] = "Resource temporarily unavailable",                           \
      [ENOMEM] = "Cannot allocate memory",                                     \
      [EACCES] = "Permission denied",                                          \
      [EFAULT] = "Bad address",                                                \
      [ENOTBLK] = "Block device required",                                     \
      [EBUSY] = "Device or resource busy",                                     \
      [EEXIST] = "File exists",                                                \
      [EXDEV] = "Invalid cross-device link",                                   \
      [ENODEV] = "No such device",                                             \
      [ENOTDIR] = "Not a directory",                                           \
      [EISDIR] = "Is a directory",                                             \
      [EINVAL] = "Invalid argument",                                           \
      [ENFILE] = "Too many open files in system",                              \
      [EMFILE] = "Too many open files",                                        \
      [ENOTTY] = "Inappropriate ioctl for device",                             \
      [ETXTBSY] = "Text file busy",                                            \
      [EFBIG] = "File too large",                                              \
      [ENOSPC] = "No space left on device",                                    \
      [ESPIPE] = "Illegal seek",                                               \
      [EROFS] = "Read-only file system",                                       \
      [EMLINK] = "Too many links",                                             \
      [EPIPE] = "Broken pipe",                                                 \
      [EDOM] = "Numerical argument out of domain",                             \
      [ERANGE] = "Numerical result out of range",                              \
      [EDEADLK] = "Resource deadlock avoided",                                 \
      [ENAMETOOLONG] = "File name too long",                                   \
      [ENOLCK] = "No locks available",                                         \
      [ENOSYS] = "Function not implemented",                                   \
      [ENOTEMPTY] = "Directory not empty",                                     \
      [ELOOP] = "Too many levels of symbolic links",                           \
      [ENOMSG] = "No message of desired type",                                 \
      [EIDRM] = "Identifier removed",                                          \
      [ECHRNG] = "Channel number out of range",                                \
      [EL2NSYNC] = "Level 2 not synchronized",                                 \
      [EL3HLT] = "Level 3 halted",                                             \
      [EL3RST] = "Level 3 reset",                                              \
      [ELNRNG] = "Link number out of range",                                   \
      [EUNATCH] = "Protocol driver not attached",                              \
      [ENOCSI] = "No CSI structure available",                                 \
      [EL2HLT] = "Level 2 halted",                                             \
      [EBADE] = "Invalid exchange",                                            \
      [EBADR] = "Invalid request descriptor",                                  \
      [EXFULL] = "Exchange full",                                              \
      [ENOANO] = "No anode",                                                   \
      [EBADRQC] = "Invalid request code",                                      \
      [EBADSLT] = "Invalid slot",                                              \
      [EDEADLOCK] = "File locking deadlock error",                             \
      [EBFONT] = "Bad font file format",                                       \
      [ENOSTR] = "Device not a stream",                                        \
      [ENODATA] = "No data available",                                         \
      [ETIME] = "Timer expired",                                               \
      [ENOSR] = "Out of streams resources",                                    \
      [ENONET] = "Machine is not on the network",                              \
      [ENOPKG] = "Package not installed",                                      \
      [EREMOTE] = "Object is remote",                                          \
      [ENOLINK] = "Link has been severed",                                     \
      [EADV] = "Advertise error",                                              \
      [ESRMNT] = "Srmount error",                                              \
      [ECOMM] = "Communication error on send",                                 \
      [EPROTO] = "Protocol error",                                             \
      [EMULTIHOP] = "Multihop attempted",                                      \
      [EDOTDOT] = "RFS specific error",                                        \
      [EBADMSG] = "Bad message",                                               \
      [EOVERFLOW] = "Value too large for defined data type",                   \
      [ENOTUNIQ] = "Name not unique on network",                               \
      [EBADFD] = "File descriptor in bad state",                               \
      [EREMCHG] = "Remote address changed",                                    \
      [ELIBACC] = "Can not access a needed shared library",                    \
      [ELIBBAD] = "Accessing a corrupted shared library",                      \
      [ELIBSCN] = ".lib section in a.out corrupted",                           \
      [ELIBMAX] = "Attempting to link in too many shared libraries",           \
      [ELIBEXEC] = "Cannot exec a shared library directly",                    \
      [EILSEQ] = "Invalid or incomplete multibyte or wide character",          \
      [ERESTART] = "Interrupted system call should be restarted",              \
      [ESTRPIPE] = "Streams pipe error",                                       \
      [EUSERS] = "Too many users",                                             \
      [ENOTSOCK] = "Socket operation on non-socket",                           \
      [EDESTADDRREQ] = "Destination address required",                         \
      [EMSGSIZE] = "Message too long",                                         \
      [EPROTOTYPE] = "Protocol wrong type for socket",                         \
      [ENOPROTOOPT] = "Protocol not available",                                \
      [EPROTONOSUPPORT] = "Protocol not supported",                            \
      [ESOCKTNOSUPPORT] = "Socket type not supported",                         \
      [EOPNOTSUPP] = "Operation not supported",                                \
      [EPFNOSUPPORT] = "Protocol family not supported",                        \
      [EAFNOSUPPORT] = "Address family not supported by protocol",             \
      [EADDRINUSE] = "Address already in use",                                 \
      [EADDRNOTAVAIL] = "Cannot assign requested address",                     \
      [ENETDOWN] = "Network is down",                                          \
      [ENETUNREACH] = "Network is unreachable",                                \
      [ENETRESET] = "Network dropped connection on reset",                     \
      [ECONNABORTED] = "Software caused connection abort",                     \
      [ECONNRESET] = "Connection reset by peer",                               \
      [ENOBUFS] = "No buffer space available",                                 \
      [EISCONN] = "Transport endpoint is already connected",                   \
      [ENOTCONN] = "Transport endpoint is not connected",                      \
      [ESHUTDOWN] = "Cannot send after transport endpoint shutdown",           \
      [ETOOMANYREFS] = "Too many references: cannot splice",                   \
      [ETIMEDOUT] = "Connection timed out",                                    \
      [ECONNREFUSED] = "Connection refused",                                   \
      [EHOSTDOWN] = "Host is down",                                            \
      [EHOSTUNREACH] = "No route to host",                                     \
      [EALREADY] = "Operation already in progress",                            \
      [EINPROGRESS] = "Operation now in progress",                             \
      [ESTALE] = "Stale file handle",                                          \
      [EUCLEAN] = "Structure needs cleaning",                                  \
      [ENOTNAM] = "Not a XENIX named type file",                               \
      [ENAVAIL] = "No XENIX semaphores available",                             \
      [EISNAM] = "Is a named type file",                                       \
      [EREMOTEIO] = "Remote I/O error",                                        \
      [EDQUOT] = "Disk quota exceeded",                                        \
      [ENOMEDIUM] = "No medium found",                                         \
      [EMEDIUMTYPE] = "Wrong medium type",                                     \
      [ECANCELED] = "Operation canceled",                                      \
      [ENOKEY] = "Required key not available",                                 \
      [EKEYEXPIRED] = "Key has expired",                                       \
      [EKEYREVOKED] = "Key has been revoked",                                  \
      [EKEYREJECTED] = "Key was rejected by service",                          \
      [EOWNERDEAD] = "Owner died",                                             \
      [ENOTRECOVERABLE] = "State not recoverable",                             \
      [ERFKILL] = "Operation not possible due to RF-kill",                     \
      [EHWPOISON] = "Memory page has hardware error",                          \
  }
#define MAX_ERRNO 133

#elif defined(_WIN32)
#define ERROR_MESSAGES                                                         \
  {                                                                            \
      [0] = "No error",                                                        \
      [1] = "Operation not permitted",                                         \
      [2] = "No such file or directory",                                       \
      [3] = "No such process",                                                 \
      [4] = "Interrupted function",                                            \
      [5] = "I/O error",                                                       \
      [6] = "No such device or address",                                       \
      [7] = "Argument list too long",                                          \
      [8] = "Exec format error",                                               \
      [9] = "Bad file number",                                                 \
      [10] = "No spawned processes",                                           \
      [11] =                                                                   \
          "No more processes or not enough memory or maximum nesting level "   \
          "reached",                                                           \
      [12] = "Not enough memory",                                              \
      [13] = "Permission denied",                                              \
      [14] = "Bad address",                                                    \
      [16] = "Device or resource busy",                                        \
      [17] = "File exists",                                                    \
      [18] = "Cross-device link",                                              \
      [19] = "No such device",                                                 \
      [20] = "Not a directory",                                                \
      [21] = "Is a directory",                                                 \
      [22] = "Invalid argument",                                               \
      [23] = "Too many files open in system",                                  \
      [24] = "Too many open files",                                            \
      [25] = "Inappropriate I/O control operation",                            \
      [27] = "File too large",                                                 \
      [28] = "No space left on device",                                        \
      [29] = "Invalid seek",                                                   \
      [30] = "Read only file system",                                          \
      [31] = "Too many links",                                                 \
      [32] = "Broken pipe",                                                    \
      [33] = "Math argument",                                                  \
      [34] = "Result too large",                                               \
      [36] = "Resource deadlock would occur",                                  \
      [38] = "Filename too long",                                              \
      [39] = "No locks available",                                             \
      [40] = "Function not supported",                                         \
      [41] = "Directory not empty",                                            \
      [42] = "Illegal sequence of bytes",                                      \
      [80] = "String was truncated",                                           \
      [100] = "Address in use",                                                \
      [101] = "Address not available",                                         \
      [102] = "Address family not supported",                                  \
      [103] = "Connection already in progress",                                \
      [104] = "Bad message",                                                   \
      [105] = "Operation canceled",                                            \
      [106] = "Connection aborted",                                            \
      [107] = "Connection refused",                                            \
      [108] = "Connection reset",                                              \
      [109] = "Destination address required",                                  \
      [110] = "Host unreachable",                                              \
      [111] = "Identifier removed",                                            \
      [112] = "Operation in progress",                                         \
      [113] = "Already connected",                                             \
      [114] = "Too many symbolic link levels",                                 \
      [115] = "Message size",                                                  \
      [116] = "Network down",                                                  \
      [117] = "Network reset",                                                 \
      [118] = "Network unreachable",                                           \
      [119] = "No buffer space",                                               \
      [120] = "No message available",                                          \
      [121] = "No link",                                                       \
      [122] = "No message",                                                    \
      [123] = "No protocol option",                                            \
      [124] = "No stream resources",                                           \
      [125] = "Not a stream",                                                  \
      [126] = "Not connected",                                                 \
      [127] = "State not recoverable",                                         \
      [128] = "Not a socket",                                                  \
      [129] = "Not supported",                                                 \
      [130] = "Operation not supported",                                       \
      [131] = "Other",                                                         \
      [132] = "Value too large",                                               \
      [133] = "Owner dead",                                                    \
      [134] = "Protocol error",                                                \
      [135] = "Protocol not supported",                                        \
      [136] = "Wrong protocol type",                                           \
      [137] = "Stream timeout",                                                \
      [138] = "Timed out",                                                     \
      [139] = "Text file busy",                                                \
      [140] = "Operation would block",                                         \
  }
#define MAX_ERRNO 140

#endif